#development:
#  adapter: mysql
#  encoding: utf8
#  database: yuno_development
#  pool: 5
#  username: root
#  password: root
#  socket: /var/run/mysqld/mysqld.sock

#test:
#  adapter: mysql
#  encoding: utf8
#  database: yuno_test
#  pool: 5
#  username: root
#  password: root
#  socket: /var/run/mysqld/mysqld.sock

#production:
#  adapter: mysql
#  encoding: utf8
#  database: yuno_production
#  pool: 5
#  username: root
#  password: root
#  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
#test:
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#  database: db/test.sqlite3
production:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/production.sqlite3
